<?php

use Illuminate\Database\Seeder;

class FieldsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('fields')->delete();
        
        \DB::table('fields')->insert(array (
            0 => 
            array (
                'id' => 1,
                'key' => 'link',
                'title' => '菜单地址',
                'type' => 'text',
                'f_module' => 'meun',
                'f_groups' => '字段分组',
                'f_description' => '菜单地址',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'key' => 'title',
                'title' => '菜单标题',
                'type' => 'text',
                'f_module' => 'meun',
                'f_groups' => '字段分组',
                'f_description' => '菜单标题',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'key' => 'icon',
                'title' => '菜单图标',
                'type' => 'text',
                'f_module' => 'meun',
                'f_groups' => '字段分组',
                'f_description' => '菜单图标',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'key' => 'description',
                'title' => '菜单描述',
                'type' => 'textarea',
                'f_module' => 'meun',
                'f_groups' => '字段分组',
                'f_description' => '菜单描述',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'key' => 'roles',
                'title' => '用户组',
                'type' => 'checkbox',
                'f_module' => 'meun',
                'f_groups' => '字段分组',
                'f_description' => '拥有权限的用户组',
                'f_options' => NULL,
                'f_ext' => 'roles',
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'key' => 'order',
                'title' => '排序',
                'type' => 'text',
                'f_module' => 'meun',
                'f_groups' => '字段分组',
                'f_description' => '排序',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'key' => 'status',
                'title' => '状态',
                'type' => 'text',
                'f_module' => 'meun',
                'f_groups' => '字段分组',
                'f_description' => '状态',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'key' => 'user_name',
                'title' => '用户名',
                'type' => 'text',
                'f_module' => 'users',
                'f_groups' => '字段分组',
                'f_description' => '用户名',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'key' => 'email',
                'title' => '邮箱',
                'type' => 'text',
                'f_module' => 'users',
                'f_groups' => '字段分组',
                'f_description' => '邮箱',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'key' => 'password',
                'title' => '用户密码',
                'type' => 'text',
                'f_module' => 'users',
                'f_groups' => '字段分组',
                'f_description' => '用户密码',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'key' => 'groups',
                'title' => '用户组',
                'type' => 'checkbox',
                'f_module' => 'users',
                'f_groups' => '字段分组',
                'f_description' => '用户组',
                'f_options' => NULL,
                'f_ext' => 'roles',
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'key' => 'status',
                'title' => '状态',
                'type' => 'select',
                'f_module' => 'users',
                'f_groups' => '字段分组',
                'f_description' => '状态，0：正常，1：锁定',
                'f_options' => '[{"title":"正常","value":0},{"title":"锁定","value":1}]',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:52',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'key' => 'name',
                'title' => '用户组名',
                'type' => 'text',
                'f_module' => 'roles',
                'f_groups' => '字段分组',
                'f_description' => '用户组名',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'key' => 'display_name',
                'title' => '显示名称',
                'type' => 'text',
                'f_module' => 'roles',
                'f_groups' => '字段分组',
                'f_description' => '显示名称',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'key' => 'thumb',
                'title' => '用户组头像',
                'type' => 'text',
                'f_module' => 'roles',
                'f_groups' => '字段分组',
                'f_description' => '用户组头像',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'key' => 'description',
                'title' => '用户组描述',
                'type' => 'text',
                'f_module' => 'roles',
                'f_groups' => '字段分组',
                'f_description' => '用户组描述',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'key' => 'status',
                'title' => '状态',
                'type' => 'select',
                'f_module' => 'roles',
                'f_groups' => '字段分组',
                'f_description' => '状态，0：正常，1：锁定',
                'f_options' => '[{"title":"正常","value":0},{"title":"锁定","value":1}]',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'key' => 'key',
                'title' => '字段key',
                'type' => 'text',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '字段key',
                'f_options' => '',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'key' => 'title',
                'title' => '字段名称',
                'type' => 'text',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '字段名称',
                'f_options' => '',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'key' => 'type',
                'title' => '字段形式',
                'type' => 'text',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '字段形式',
                'f_options' => '',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'key' => 'f_module',
                'title' => '所属模块',
                'type' => 'text',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '所属模块',
                'f_options' => '',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'key' => 'f_groups',
                'title' => '字段分组',
                'type' => 'text',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '字段分组',
                'f_options' => '',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'key' => 'f_description',
                'title' => '字段描述',
                'type' => 'textarea',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '字段描述',
                'f_options' => '',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'key' => 'f_options',
                'title' => '字段设置',
                'type' => 'textarea',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '字段设置',
                'f_options' => '',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'key' => 'f_default',
                'title' => '默认值',
                'type' => 'textarea',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '默认值',
                'f_options' => '',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'key' => 'order',
                'title' => '排序',
                'type' => 'text',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '排序',
                'f_options' => '',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'key' => 'status',
                'title' => '状态',
                'type' => 'select',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '状态，0：正常，1：锁定',
                'f_options' => '[{"title":"正常","value":0},{"title":"锁定","value":1}]',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'key' => 'f_add',
                'title' => '新增权限',
                'type' => 'checkbox',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '新增权限',
                'f_options' => NULL,
                'f_ext' => 'roles',
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'key' => 'f_edit',
                'title' => '编辑权限',
                'type' => 'checkbox',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '编辑权限',
                'f_options' => '[{"title":"正常","value":0},{"title":"锁定","value":1}]',
                'f_ext' => 'roles',
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'key' => 'f_visible',
                'title' => '可见权限',
                'type' => 'checkbox',
                'f_module' => 'fields',
                'f_groups' => '字段分组',
                'f_description' => '可见权限',
                'f_options' => NULL,
                'f_ext' => 'roles',
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'key' => 'name',
                'title' => '权限key',
                'type' => 'select',
                'f_module' => 'role_permissions',
                'f_groups' => '字段分组',
                'f_description' => '权限key',
                'f_options' => NULL,
                'f_ext' => 'permts',
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'key' => 'display_name',
                'title' => '权限名称',
                'type' => 'text',
                'f_module' => 'permissions',
                'f_groups' => '字段分组',
                'f_description' => '权限名称',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'key' => 'group',
                'title' => '权限分组',
                'type' => 'text',
                'f_module' => 'permissions',
                'f_groups' => '字段分组',
                'f_description' => '权限分组',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'key' => 'roles',
                'title' => '用户组',
                'type' => 'checkbox',
                'f_module' => 'permissions',
                'f_groups' => '字段分组',
                'f_description' => '用户组',
                'f_options' => NULL,
                'f_ext' => 'roles',
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'key' => 'description',
                'title' => '权限描述',
                'type' => 'text',
                'f_module' => 'permissions',
                'f_groups' => '字段分组',
                'f_description' => '权限描述',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'key' => 'title',
                'title' => '标题',
                'type' => 'text',
                'f_module' => 'article',
                'f_groups' => '字段分组',
                'f_description' => '标题',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'key' => 'keyword',
                'title' => '关键词',
                'type' => 'text',
                'f_module' => 'article',
                'f_groups' => '字段分组',
                'f_description' => '关键词',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'key' => 'category',
                'title' => '文章分类',
                'type' => 'select',
                'f_module' => 'article',
                'f_groups' => '字段分组',
                'f_description' => '文章分类',
                'f_options' => NULL,
                'f_ext' => 'category',
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'key' => 'tags',
                'title' => '文章标签',
                'type' => 'checkbox',
                'f_module' => 'article',
                'f_groups' => '字段分组',
                'f_description' => '文章标签',
                'f_options' => NULL,
                'f_ext' => 'tags',
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'key' => 'excerpt',
                'title' => '简介',
                'type' => 'textarea',
                'f_module' => 'article',
                'f_groups' => '字段分组',
                'f_description' => '简介',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'key' => 'thumb',
                'title' => '缩略图',
                'type' => 'upload',
                'f_module' => 'article',
                'f_groups' => '字段分组',
                'f_description' => '缩略图',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'key' => 'content',
                'title' => '内容',
                'type' => 'editer',
                'f_module' => 'article',
                'f_groups' => '字段分组',
                'f_description' => '内容',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'key' => 'order',
                'title' => '排序',
                'type' => 'text',
                'f_module' => 'article',
                'f_groups' => '字段分组',
                'f_description' => '排序',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'key' => 'category_name',
                'title' => '分类名称',
                'type' => 'text',
                'f_module' => 'article_category',
                'f_groups' => '字段分组',
                'f_description' => '分类名称',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'key' => 'category_ico',
                'title' => '分类图标',
                'type' => 'text',
                'f_module' => 'article_category',
                'f_groups' => '字段分组',
                'f_description' => '分类图标',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'key' => 'category_des',
                'title' => '分类描述',
                'type' => 'textarea',
                'f_module' => 'article_category',
                'f_groups' => '字段分组',
                'f_description' => '分类描述',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'key' => 'pid',
                'title' => '上级分类',
                'type' => 'select',
                'f_module' => 'article_category',
                'f_groups' => '字段分组',
                'f_description' => '上级分类',
                'f_options' => NULL,
                'f_ext' => 'category',
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'key' => 'taxonomy',
                'title' => '所属分类法',
                'type' => 'select',
                'f_module' => 'article_category',
                'f_groups' => '字段分组',
                'f_description' => '所属分类法',
                'f_options' => '[{"title":"栏目分类","value":"category"},{"title":"标签tags","value":"tags"}]',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'key' => 'status',
                'title' => '状态',
                'type' => 'select',
                'f_module' => 'article_category',
                'f_groups' => '字段分组',
                'f_description' => '状态',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'key' => 'content',
                'title' => '评论内容',
                'type' => 'textarea',
                'f_module' => 'chat',
                'f_groups' => '字段分组',
                'f_description' => '评论内容',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'key' => 'username',
                'title' => '用户名',
                'type' => 'text',
                'f_module' => 'chat',
                'f_groups' => '字段分组',
                'f_description' => '用户名',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'key' => 'user_id',
                'title' => '用户ID',
                'type' => 'text',
                'f_module' => 'chat',
                'f_groups' => '字段分组',
                'f_description' => '用户ID',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'key' => 'head_img',
                'title' => '用户头像',
                'type' => 'text',
                'f_module' => 'chat',
                'f_groups' => '字段分组',
                'f_description' => '用户头像',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'key' => 'time',
                'title' => '发布时间',
                'type' => 'text',
                'f_module' => 'chat',
                'f_groups' => '字段分组',
                'f_description' => '发布时间',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'key' => 'title',
                'title' => '话题标题',
                'type' => 'text',
                'f_module' => 'topic',
                'f_groups' => '字段分组',
                'f_description' => '话题标题',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'key' => 'content',
                'title' => '话题内容',
                'type' => 'textarea',
                'f_module' => 'topic',
                'f_groups' => '字段分组',
                'f_description' => '话题内容',
                'f_options' => NULL,
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'key' => 'status',
                'title' => '状态',
                'type' => 'select',
                'f_module' => 'topic',
                'f_groups' => '字段分组',
                'f_description' => '状态，0：正常，1：锁定',
                'f_options' => '[{"title":"正常","value":0},{"title":"锁定","value":1}]',
                'f_ext' => NULL,
                'f_default' => NULL,
                'f_add' => '[1]',
                'f_edit' => '[1]',
                'f_visible' => '[1]',
                'order' => 0,
                'status' => 0,
                'created_at' => '2016-09-24 12:20:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}
